### ISSUE TITLE
Crash in ONEPLUS A6010

### ISSUE THREAD

**Issue by sachithkadamba** [kalontech/ReactNativeWheelPicker#107]
java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
  at java.util.ArrayList.get(ArrayList.java:439)
  at com.wheelpicker.LoopRunnable.run(LoopRunnable.java:16)
  at android.os.Handler.handleCallback(Handler.java:873)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:193)
  at android.app.ActivityThread.main(ActivityThread.java:6863)
  at java.lang.reflect.Method.invoke(Method.java:-2)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by ArtemKosiakevych** [comment]
Can you share steps to reproduce and some code?

**Comment by ArtemKosiakevych** [comment]
closing, missing info
