### ISSUE TITLE
crashing in Android

### ISSUE THREAD

**Issue by mayooresan** [kalontech/ReactNativeWheelPicker#122]
Thanks for this library, though it works fine on iOS it fails on Android. I get this error on the metro console.

````
Loading dependency graph...events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, scandir '/Users/kavinie/Documents/newton/CL_Covid19_Mobile_App/android/app/build/generated/not_namespaced_r_class_sources/debug/r/com/facebook/drawee/backends'
Emitted 'error' event at:
    at Walker.emit (events.js:198:13)
    at /Users/kavinie/Documents/newton/CL_Covid19_Mobile_App/node_modules/walker/lib/walker.js:63:18
    at go$readdir$cb (/Users/kavinie/Documents/newton/CL_Covid19_Mobile_App/node_modules/graceful-fs/graceful-fs.js:162:14)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
````

**Comment by mayooresan** [comment]
Actually this error occurred due to improper setup. I've fixed it.
